#!/bin/bash
set -e

mysql -uroot -p"$MYSQL_ROOT_PASSWORD" <<-EOSQL
    CREATE DATABASE IF NOT EXISTS $AIRFLOW_DB;
    GRANT ALL PRIVILEGES ON $AIRFLOW_DB.* TO '$AIRFLOW_USER'@'%' IDENTIFIED BY '$AIRFLOW_PASSWORD';
    CREATE DATABASE IF NOT EXISTS $METABASE_DB;
    GRANT ALL PRIVILEGES ON $METABASE_DB.* TO '$METABASE_USER'@'%' IDENTIFIED BY '$METABASE_PASSWORD';
    CREATE DATABASE IF NOT EXISTS $FAKER_DB;
    GRANT ALL PRIVILEGES ON $FAKER_DB.* TO '$FAKER_USER'@'%' IDENTIFIED BY '$FAKER_PASSWORD';
    FLUSH PRIVILEGES;
EOSQL
